-- Seed frequently used vehicle models for available brands

with model_data as (
  select * from (values
    -- Binek markalar
    ('AUDI', 'A3'),
    ('AUDI', 'A4'),
    ('AUDI', 'A6'),
    ('AUDI', 'Q3'),
    ('AUDI', 'Q5'),
    ('AUDI', 'Q8'),
    ('BMW', '116i'),
    ('BMW', '320i'),
    ('BMW', '520d'),
    ('BMW', 'X3'),
    ('BMW', 'X5'),
    ('BMW', 'X7'),
    ('MERCEDES', 'A 200'),
    ('MERCEDES', 'C 200'),
    ('MERCEDES', 'E 200'),
    ('MERCEDES', 'GLA 200'),
    ('MERCEDES', 'GLE 350'),
    ('MERCEDES', 'S 400'),
    ('VOLKSWAGEN', 'Polo'),
    ('VOLKSWAGEN', 'Golf'),
    ('VOLKSWAGEN', 'Passat'),
    ('VOLKSWAGEN', 'Tiguan'),
    ('VOLKSWAGEN', 'Touareg'),
    ('VOLKSWAGEN', 'ID.3'),
    ('TOYOTA', 'Yaris'),
    ('TOYOTA', 'Corolla'),
    ('TOYOTA', 'Camry'),
    ('TOYOTA', 'C-HR'),
    ('TOYOTA', 'RAV4'),
    ('TOYOTA', 'Land Cruiser'),
    ('RENAULT', 'Clio'),
    ('RENAULT', 'Megane Sedan'),
    ('RENAULT', 'Taliant'),
    ('RENAULT', 'Captur'),
    ('RENAULT', 'Kadjar'),
    ('RENAULT', 'Austral'),
    ('FORD', 'Fiesta'),
    ('FORD', 'Focus'),
    ('FORD', 'Mondeo'),
    ('FORD', 'Kuga'),
    ('FORD', 'Ranger'),
    ('FORD', 'Transit Custom'),
    ('OPEL', 'Corsa'),
    ('OPEL', 'Astra'),
    ('OPEL', 'Insignia'),
    ('OPEL', 'Crossland'),
    ('OPEL', 'Mokka'),
    ('OPEL', 'Grandland'),
    ('PEUGEOT', '208'),
    ('PEUGEOT', '308'),
    ('PEUGEOT', '508'),
    ('PEUGEOT', '2008'),
    ('PEUGEOT', '3008'),
    ('PEUGEOT', '5008'),
    ('CITROEN', 'C3'),
    ('CITROEN', 'C4'),
    ('CITROEN', 'C5 Aircross'),
    ('CITROEN', 'C-Elysee'),
    ('CITROEN', 'Berlingo'),
    ('CITROEN', 'Jumpy'),
    ('FIAT', 'Egea Sedan'),
    ('FIAT', 'Egea Hatchback'),
    ('FIAT', '500X'),
    ('FIAT', 'Doblo'),
    ('FIAT', 'Fiorino'),
    ('FIAT', 'Tipo Cross'),
    ('HONDA', 'Civic Sedan'),
    ('HONDA', 'Civic Hatchback'),
    ('HONDA', 'Accord'),
    ('HONDA', 'HR-V'),
    ('HONDA', 'CR-V'),
    ('HONDA', 'ZR-V'),
    ('HYUNDAI', 'i10'),
    ('HYUNDAI', 'i20'),
    ('HYUNDAI', 'i30'),
    ('HYUNDAI', 'Tucson'),
    ('HYUNDAI', 'Santa Fe'),
    ('HYUNDAI', 'Kona'),
    ('KIA', 'Rio'),
    ('KIA', 'Ceed'),
    ('KIA', 'Cerato'),
    ('KIA', 'Sportage'),
    ('KIA', 'Sorento'),
    ('KIA', 'Stonic'),
    ('VOLVO', 'S60'),
    ('VOLVO', 'S90'),
    ('VOLVO', 'V60'),
    ('VOLVO', 'XC40'),
    ('VOLVO', 'XC60'),
    ('VOLVO', 'XC90'),
    ('NISSAN', 'Micra'),
    ('NISSAN', 'Qashqai'),
    ('NISSAN', 'Juke'),
    ('NISSAN', 'X-Trail'),
    ('NISSAN', 'Navara'),
    ('NISSAN', 'Leaf'),
    ('SKODA', 'Fabia'),
    ('SKODA', 'Scala'),
    ('SKODA', 'Octavia'),
    ('SKODA', 'Superb'),
    ('SKODA', 'Karoq'),
    ('SKODA', 'Kodiaq'),
    ('SEAT', 'Ibiza'),
    ('SEAT', 'Leon'),
    ('SEAT', 'Ateca'),
    ('SEAT', 'Arona'),
    ('SEAT', 'Tarraco'),
    ('SEAT', 'Toledo'),
    ('ALFA ROMEO', 'Giulia'),
    ('ALFA ROMEO', 'Giulietta'),
    ('ALFA ROMEO', 'Stelvio'),
    ('ALFA ROMEO', 'Tonale'),
    ('ALFA ROMEO', '4C'),
    ('ALFA ROMEO', 'MiTo'),
    ('MAZDA', 'Mazda2'),
    ('MAZDA', 'Mazda3'),
    ('MAZDA', 'Mazda6'),
    ('MAZDA', 'CX-3'),
    ('MAZDA', 'CX-5'),
    ('MAZDA', 'CX-60'),
    ('MITSUBISHI', 'Attrage'),
    ('MITSUBISHI', 'Lancer'),
    ('MITSUBISHI', 'ASX'),
    ('MITSUBISHI', 'Eclipse Cross'),
    ('MITSUBISHI', 'Outlander'),
    ('MITSUBISHI', 'L200'),
    ('SUZUKI', 'Swift'),
    ('SUZUKI', 'Baleno'),
    ('SUZUKI', 'Vitara'),
    ('SUZUKI', 'S-Cross'),
    ('SUZUKI', 'Jimny'),
    ('SUZUKI', 'Ignis'),
    ('SUBARU', 'Impreza'),
    ('SUBARU', 'Legacy'),
    ('SUBARU', 'XV'),
    ('SUBARU', 'Forester'),
    ('SUBARU', 'Outback'),
    ('SUBARU', 'Levorg'),
    ('MINI COOPER', '3 Door'),
    ('MINI COOPER', '5 Door'),
    ('MINI COOPER', 'Clubman'),
    ('MINI COOPER', 'Countryman'),
    ('MINI COOPER', 'Cabrio'),
    ('MINI COOPER', 'Electric'),
    ('TESLA', 'Model 3'),
    ('TESLA', 'Model S'),
    ('TESLA', 'Model X'),
    ('TESLA', 'Model Y'),
    ('TESLA', 'Cybertruck'),
    ('TESLA', 'Roadster'),
    ('TOGG', 'T10X V1'),
    ('TOGG', 'T10X V2'),
    ('TOGG', 'T10X L'),
    ('TOGG', 'T10F'),
    ('TOGG', 'Sedan Konsept'),
    ('TOGG', 'Fastback Konsept'),
    ('JEEP', 'Renegade'),
    ('JEEP', 'Compass'),
    ('JEEP', 'Cherokee'),
    ('JEEP', 'Grand Cherokee'),
    ('JEEP', 'Wrangler'),
    ('JEEP', 'Gladiator'),
    ('LAND', 'Range Rover Evoque'),
    ('LAND', 'Range Rover Sport'),
    ('LAND', 'Defender'),
    ('LAND', 'Discovery'),
    ('LAND', 'Discovery Sport'),
    ('LAND', 'Range Rover Velar'),
    ('CHERY', 'Tiggo 7'),
    ('CHERY', 'Tiggo 8'),
    ('CHERY', 'Tiggo 9'),
    ('CHERY', 'Omoda 5'),
    ('CHERY', 'Omoda 3'),
    ('CHERY', 'Arrizo 8'),
    ('CHEVROLET', 'Spark'),
    ('CHEVROLET', 'Aveo'),
    ('CHEVROLET', 'Cruze'),
    ('CHEVROLET', 'Malibu'),
    ('CHEVROLET', 'Captiva'),
    ('CHEVROLET', 'Trailblazer'),
    ('DACIA', 'Sandero'),
    ('DACIA', 'Sandero Stepway'),
    ('DACIA', 'Duster'),
    ('DACIA', 'Jogger'),
    ('DACIA', 'Spring'),
    ('DACIA', 'Logan'),
    ('DAEWOO', 'Lanos'),
    ('DAEWOO', 'Nubira'),
    ('DAEWOO', 'Leganza'),
    ('DAEWOO', 'Matiz'),
    ('DAEWOO', 'Espero'),
    ('DAEWOO', 'Kalos'),
    ('DFM/SUZUKI', 'Carry'),
    ('DFM/SUZUKI', 'Super Carry'),
    ('DFM/SUZUKI', 'Panelvan'),
    ('DFM/SUZUKI', 'Minibüs'),
    ('DFM/SUZUKI', 'Kamyonet'),
    ('DFM/SUZUKI', 'SoCool'),
    -- Ticari ve ağır vasıta
    ('MAN', 'TGX 18.440'),
    ('MAN', 'TGX 18.480'),
    ('MAN', 'TGS 18.430'),
    ('MAN', 'TGS 26.500'),
    ('MAN', 'TGM 18.290'),
    ('MAN', 'TGL 12.250'),
    ('SCANIA', 'R410'),
    ('SCANIA', 'R450'),
    ('SCANIA', 'R500'),
    ('SCANIA', 'S500'),
    ('SCANIA', 'S650'),
    ('SCANIA', 'G410'),
    ('VOLVO', 'FH 460'),
    ('VOLVO', 'FH 500'),
    ('VOLVO', 'FH 540'),
    ('VOLVO', 'FM 460'),
    ('VOLVO', 'FMX 540'),
    ('VOLVO', 'FE 320'),
    ('BMC', 'Pro 1144'),
    ('BMC', 'Pro 827'),
    ('BMC', 'Tuğra TGR 1832'),
    ('BMC', 'Tuğra TGR 1840'),
    ('BMC', 'Neocity'),
    ('BMC', 'Procity'),
    ('ISUZU', 'D-Max'),
    ('ISUZU', 'N-Series'),
    ('ISUZU', 'F-Series'),
    ('ISUZU', 'Turkuaz'),
    ('ISUZU', 'Visigo'),
    ('ISUZU', 'Citiport'),
    ('OTOKAR', 'Doruk'),
    ('OTOKAR', 'Kent'),
    ('OTOKAR', 'Sultan'),
    ('OTOKAR', 'Territo'),
    ('OTOKAR', 'Navigo'),
    ('OTOKAR', 'Vectio'),
    ('KARSAN', 'Jest'),
    ('KARSAN', 'Atak'),
    ('KARSAN', 'e-Atak'),
    ('KARSAN', 'e-Jest'),
    ('KARSAN', 'Citymood'),
    ('KARSAN', 'Mega'),
    ('TEMSA', 'Avenue'),
    ('TEMSA', 'Prestij'),
    ('TEMSA', 'Maraton'),
    ('TEMSA', 'HD12'),
    ('TEMSA', 'MD9'),
    ('TEMSA', 'LD SB'),
    ('HIDROMEK', 'HMK 102B'),
    ('HIDROMEK', 'HMK 220LC'),
    ('HIDROMEK', 'HMK 300LC'),
    ('HIDROMEK', 'HMK 640WL'),
    ('HIDROMEK', 'HMK 140W'),
    ('HIDROMEK', 'HMK 370LC'),
    -- Tarım ve iş makineleri
    ('NEW HOLLAND', 'T4.75'),
    ('NEW HOLLAND', 'T5.105'),
    ('NEW HOLLAND', 'T6.155'),
    ('NEW HOLLAND', 'T7.210'),
    ('NEW HOLLAND', 'TT4.75'),
    ('NEW HOLLAND', 'TD5.95'),
    ('MASSEY FERGUSON', 'MF 2600'),
    ('MASSEY FERGUSON', 'MF 4700'),
    ('MASSEY FERGUSON', 'MF 5700'),
    ('MASSEY FERGUSON', 'MF 6700'),
    ('MASSEY FERGUSON', 'MF 7700'),
    ('MASSEY FERGUSON', 'MF 8700'),
    ('JOHN DEERE', '5E 75'),
    ('JOHN DEERE', '5M 110'),
    ('JOHN DEERE', '6M 155'),
    ('JOHN DEERE', '6R 215'),
    ('JOHN DEERE', '7R 290'),
    ('JOHN DEERE', '8R 340'),
    ('DEUTZ', 'Agroplus 410'),
    ('DEUTZ', 'Agrofarm 420'),
    ('DEUTZ', 'Agrotron 6155'),
    ('DEUTZ', 'Agrotron 7250'),
    ('DEUTZ', '6G 140'),
    ('DEUTZ', '7G 250'),
    ('VALTRA', 'A104'),
    ('VALTRA', 'A114'),
    ('VALTRA', 'N124'),
    ('VALTRA', 'N154'),
    ('VALTRA', 'T174'),
    ('VALTRA', 'T234'),
    ('LANDINI', 'Powerfarm 110'),
    ('LANDINI', '6-140'),
    ('LANDINI', '7-160'),
    ('LANDINI', 'Rex 120'),
    ('LANDINI', 'Super 8860'),
    ('LANDINI', 'Legend 115'),
    ('ERKUNT', 'Bereket 70'),
    ('ERKUNT', 'Nimet 75'),
    ('ERKUNT', 'Bereket 90'),
    ('ERKUNT', 'Nimet 110'),
    ('ERKUNT', 'Servet 110'),
    ('ERKUNT', 'Boran 110'),
    ('TUMOSAN', '50.50'),
    ('TUMOSAN', '60.60'),
    ('TUMOSAN', '70.70'),
    ('TUMOSAN', '80.80'),
    ('TUMOSAN', '9105'),
    ('TUMOSAN', '9115'),
    ('HATTAT', 'B3065'),
    ('HATTAT', 'B4080'),
    ('HATTAT', 'T4100'),
    ('HATTAT', 'T4125'),
    ('HATTAT', 'T4135'),
    ('HATTAT', 'T4145'),
    ('BASAK', '2075 S'),
    ('BASAK', '2090 S'),
    ('BASAK', '2110 S'),
    ('BASAK', '2090'),
    ('BASAK', '2105'),
    ('BASAK', '5120'),
    ('CASE IH', 'Farmall 55C'),
    ('CASE IH', 'Farmall 75C'),
    ('CASE IH', 'Maxxum 125'),
    ('CASE IH', 'Puma 155'),
    ('CASE IH', 'Optum 300'),
    ('CASE IH', 'Magnum 310'),
    ('JCB', '3CX'),
    ('JCB', '4CX'),
    ('JCB', 'JS220'),
    ('JCB', '205T'),
    ('JCB', '455 ZX'),
    ('JCB', 'TM320')
  ) as t(brand_name, model_name)
)
insert into vehicle_models (name, brand_id, is_active)
select md.model_name, vb.id, true
from model_data md
join vehicle_brands vb
  on upper(vb.name) = md.brand_name
on conflict (name, brand_id) do nothing;
